### ISSUE TITLE
Cloud execution

### ISSUE THREAD

**Issue by TMiguelT** [scipipe/scipipe#110]
Hi. I've looked through the docs and there doesn't seem to be any particular reference on if this is possible. What I'm envisaging is having each process run via [AWS Batch](https://aws.amazon.com/batch/) or the [Google Cloud Life Sciences API](https://cloud.google.com/life-sciences/docs/quickstart), which are common targets for bioinformatics pipelines.

**Comment by jonalv** [comment]
There was a bit of work on similar things at some point but nothing finished as far as I know. I think in theory there is nothing stopping it except that there is implementation to do. But Samuel know better. 
I am simply running in one giant pod on our Kubernetes cluster but that does not scale beyond what I am already doing.

**Comment by samuell** [comment]
Thanks @jonalv for answering! :+1: 

@TMiguelT Yes, just as @jonalv said, there is not much implemented in terms of that yet.

There are some great ideas about how to implement a generic remote execution mechanism suggested by @kwrobert in #53, for anyone wanting to contribute (or paying me for working on it on @savantic time :slightly_smiling_face:). Otherwise it will probably be implemented eventually, but can't guarantee a time plan for it at the moment unfortunately.

**Comment by samuell** [comment]
@TMiguelT Closing for now, and suggest continuing further discussion in #53 as there's a lot of overlap. Cheers!
