### ISSUE TITLE
Why Go?

### ISSUE THREAD

**Issue by rizplate** [scipipe/scipipe#59]
What advantages you think Go has for data processing over python?
why should someone learn another language, just for using your pipeline?

**Comment by samuell** [comment]
Hi @rizplate and thanks for your question!

I think this is a very relevant question, as python is a much more popular language in data science, and in bioinformatics in particular.

There are a number of reasons why we switched to Go, after using the python-based [Luigi engine](https://github.com/spotify/luigi), with our helper library [SciLuigi](https://github.com/pharmbio/sciluigi) on top:

## Performance

Firstly, it running each task concurrently in a "light-weight thread" (coroutine, or goroutine) instead of completely separate python processes. This allows us to keep thousands of tasks in their own goroutines, without performance problems, while in Luigi, we got communication problems between the processes when going over 64 workers. Go is also in general very performant, as being a compiled language, that has gotten a lot of optimization work by Google engineers.

This is the primary driving reason for our switch. Then there are a number of other factors that play in as well:

## Catching errors early

With Luigi, we often had many small bugs show up only when running a workflow. Sometimes a HPC job would fail on the 7th day of a 7-day run, just because of a simple dict key error. With Go, since it is compiled, we catch much more of these simple bugs already at compile time.

## An excellent dataflow / flow-based programming language

Also, we realized that the concurrency primitives in Go (channels, goroutines etc) makes it really easy to create scheduling code which is very very easy to reason about, by letting the workflow be a dataflow network, that acts as an "implicity scheduler". I recommend to read more about [Flow-based programming](https://github.com/samuell/awesome-fbp) to understand the benetifs of this.

## Robustness

Then, our experience with Go after the first experimentation was very positive: Go turned out to be a much more robust and less error-prone language to work with, in the long run. This is due to a number of reasons:

- It is a compiled language, catching errors early
- The language is small and simple, meaning that you can often easily understand your code when you return a few weeks later
- A lot of funcitonality is available in the standard library, lessening the need to rely on external dependencies, that might suddently change or break
- It comes with a lot of important tooling in the official package (built in testing, code formatting, checking, race detection, etc etc)

## More pointers on Go for data science

For more on other people's experience with Go, compared to e.g. python, for Data Science, I'd recommend @dwhitena's GopherCon talk:

- [GopherCon 2016: Daniel Whitenack - Go for Data Science](https://www.youtube.com/watch?v=D5tDubyXLrQ)

It also turns out Go is becoming a popular language for workflow frameworks. We wrote up a post comparing four recent Go-based workflow systems here:

- [More Go-based Workflow Tools in Bioinformatics](http://gopherdata.io/post/more_go_based_workflow_tools_in_bioinformatics/)

Ok, that's a few pointers. Hope it helps!

**Comment by rizplate** [comment]
#### Performance
Python also have light-weight threads, eventlets, gevets etc. Unless it is a non-blocking app, mostly for udp type processing i.e. voice or video, where data loss is acceptable, using  "light-weight thread" (coroutine, or goroutine) which assume that each unit of work is very very short, is really not a good solution. Threads are good for workload that is blocking , for any amount of time, which is the case for all data processing applications. So I do not buy that for processing large amount of scientific data we need eventloop type of processing. Event type processing is only good for small payload udp type processing where processing is finished in few millisecond i.e. chat/voice/video-frames etc. Coroutines are not created for data flow scheduling, they were created for scheduling small processor workload on different **cores** of cpu, this is not the scheduling that luigi does.

#### Bugs/Errors/Roubustness etc
Python has mature, decades old, battle tested frameworks and runtime. The reason for popularity of Python is that it is the easiest language, easier that javascript or anything else. The difficulty is not that it is easier to debug in python vs go. It is that distributed systems are hard. I am very familiar with luigi, ariflow, joblib and all the animals in hadoop zoo. The reason is that it is difficult to program and understand and do logging in distributed systems. I am not aware of any good distributed frameworks in go except some maybe some Amazon tools, everything else is written in Java/JVM due to maturity of ecosystem. It will be a huge amount of efforts or years

#### Libraries
Python has a huge ecosystem, python std library is very mature, more mature than Java. Most of the code in scientific and data world is written in python. It will be a huge rewriting effort or working with bad libraries (similar to pathetic state of libraries in javascript ecosystem).

I will not be using it or recommending it, however do keep at it for your learning experience.

**Comment by samuell** [comment]
Thanks for your honest feedback @rizplate. A few comments:

> Python also have light-weight threads, eventlets, gevets etc. Unless it is a non-blocking app, mostly for udp type processing i.e. voice or video, where data loss is acceptable, using "light-weight thread" (coroutine, or goroutine) which assume that each unit of work is very very short, is really not a good solution. Threads are good for workload that is blocking , for any amount of time, which is the case for all data processing applications. So I do not buy that for processing large amount of scientific data we need eventloop type of processing. Event type processing is only good for small payload udp type processing where processing is finished in few millisecond i.e. chat/voice/video-frames etc. Coroutines are not created for data flow scheduling, they were created for scheduling small processor workload on different cores of cpu, this is not the scheduling that luigi does.

Python coroutines and Go's goroutines are very different under the hood. Python coroutines all happen on the same core, while Go automatically multiplexes goroutines onto physical cores. For blocking system calls, it automatically creates extra threads, so as not to block the main program. This means that blocking operations are not suited for python's coroutines, but work very well with Go's goroutines.

> I am not aware of any good distributed frameworks in go except some maybe some Amazon tools, everything else is written in Java/JVM due to maturity of ecosystem.

For distributed frameworks, I suggest checking out: [Nats](https://nats.io/), [Vice](https://github.com/matryer/vice) and possibly [Glow](https://github.com/chrislusf/glow) and [Gleam](https://github.com/chrislusf/gleam).

(For workflows, I already referred to a post mentioning [Pachyderm](http://pachyderm.io), [Reflow](https://github.com/grailbio/reflow) and [AWE](https://github.com/MG-RAST/AWE)). 

> It will be a huge rewriting effort or working with bad libraries (similar to pathetic state of libraries in javascript ecosystem).

Go has a very extensive set of functionality in its standard library. As a small example, I was [blown away by the excellent XML parsing support](http://bionics.it/posts/parsing-drugbank-xml-or-any-large-xml-file-in-streaming-mode-in-go), which was more powerful and performant (while simple), than anything I've worked with in Python.

It also has a fast growing [ecosystem of data science libraries](https://github.com/gopherdata/resources/tree/master/tooling).

> I will not be using it or recommending it, however do keep at it though , for your learning experience.

I agree that probably a lot of people will stick to Python for a long time to come, because of its easier syntax. I primarily develop this tool to solve my/our own problems though, and went with Go because of a frustration with Python (as much as I love the language as such). SciPipe is as such, my own dream-tool for building workflows. If anybody else finds it useful, that'll be bonus points :slightly_smiling_face:

**Comment by rmanicav** [comment]
Hi,
I am getting below errors when running the file
download.SetPathStatic undefined (type *scipipe.Process has no field or method SetPathStatic)
./drug_feature_extract.go:24:7: unzip.SetPathStatic undefined (type *scipipe.Process has no field or method SetPathStatic)
./drug_feature_extract.go:28:10: xmlToTSV.SetPathExtend undefined (type *scipipe.Process has no field or method SetPathExtend)

Any guidance will be really helpful.

Thanks,
Rajesh

**Comment by samuell** [comment]
Hi @rmanicav ,

Ah, I suppose you are trying out the [DrugBank XML post](https://bionics.it/posts/parsing-drugbank-xml-or-any-large-xml-file-in-streaming-mode-in-go).

I realize I haven't updated the syntax in that post to the latest SciPipe syntax.

E.g. `SetPathStatic()` should be `SetOut()` now.

I'll have a look at updating the post asap.

Best Regards

**Comment by rmanicav** [comment]
Thank you so much. It fixed the error.
