### ISSUE TITLE
Can not use a variable in an absolute path

### ISSUE THREAD

**Issue by PaschalisAthan** [scipipe/scipipe#70]
Hello, I am rather new with both Go and Scipipe but I came up with an issue I am not sure how to solve.
I am trying to create a pipeline where I want to import all the files that are in a folder and use those files in other procedures.

My though was to first create a list with the filenames of the files in the specific folder and then assign each of those to a variable and use that variable for both "targeting" the correct file (using absolute path for example) and giving each output file a different name depending the initial filename. My code goes like this:

```go
package main

import (
	"io/ioutil"
	"log"

	sp "github.com/scipipe/scipipe"
)

func main() {
	files, err := ioutil.ReadDir(".")
	if err != nil {
		log.Fatal(err)
	}

	var td []string

	for _, f := range files {
		td = append(td, f.Name()) // Creating a list with the filenames
	}
	td = append(td[:0], td[1], td[2], td[3]) // I removed the .DS_Store file I was getting in the list

	wf := sp.NewWorkflow("DB", 1)

	for _, target := range td {
		train_proc := wf.NewProc(target+"_train", `echo "$(cat ~/Desktop/Project/'$target')" > {o:out}`)
		train_proc.SetOut("out", target+"_file.txt")
	}

	wf.Run()
}
```

I actually want to take the content of a file and copy it to an output file, but I can't find a way to **point** to the file with the specific name while using a variable in the absolute path of that file.
In the SetOut stage, the *target* variable is replaced by the different values

Thank you in advance

**Comment by samuell** [comment]
Hi @PaschalisAthan , Cool that you got going with SciPipe (and Go)! It can defenitely be a little bit of a ramp up step to get started with everything ... so don't despair :D

For your problem, I recommend having a look at the [FileGlobber component](https://godoc.org/github.com/scipipe/scipipe/components#FileGlobber). It enables you to set a "globbing", or "wildcard matching" pattern to match all the files in the directory, and generate a stream of those, on its outport.

Here is a small example program that takes all files in the directory "mydir", provided it is just beneath the directory where you go script is, and replaces 'h' with 'H' with them:

```go
package main

import (
	sp "github.com/scipipe/scipipe"
	spc "github.com/scipipe/scipipe/components"
)

func main() {
	wf := sp.NewWorkflow("my_wf", 4)
	filesInDirectory := spc.NewFileGlobber(wf, "files_in_dir", "mydir/*")

	hReplacer := wf.NewProc("h_replacer", "cat {i:in} | sed 's/h/H/g' > {o:out}")
	hReplacer.In("in").From(filesInDirectory.Out())

	wf.Run()
}
```

(I created the test file for this, with the following lines of bash:

```bash
mkdir mydir
for word in hi hej hola; do echo $word > mydir/$word.txt; done
```

Btw, I recommend using the `go fmt` tool to format go code. I think if you use the [Visual Studio Code](https://code.visualstudio.com/) editor with Microsoft's [Go plugin](https://code.visualstudio.com/), it might do this automatically on save (otherwise one can configure it to do so).

**Comment by samuell** [comment]
@PaschalisAthan Wait, sorry, I see I missed to answer your question there ... looking at answerin that shortly ...

**Comment by samuell** [comment]
> I actually want to take the content of a file and copy it to an output file, but I can't find a way to point to the file with the specific name while using a variable in the absolute path of that file.
In the SetOut stage, the target variable is replaced by the different values

In short, one can say that working with absolute paths is a bit against how scipipe encourages you to work. This is because that will make your workflow less dynamic to changes. Instead, scipipe tries to manage all of the file naming and munging for you, as long as you define how your dependencies go, and where you get your files from.

The idea is instead to get the concrete filenames into commands by using the `{i:inport-name}` syntax in commands. as explained [here in the docs](http://scipipe.org/writing_workflows/#the-shell-command-pattern).
This `{i:inport-name}` syntax is also available when setting output paths with `SetOut()`, so to do something similar to what I think you were trying to do, using the FileGlobber component as I suggested above, it might look something like this:

```go
package main

import (
	// Import scipipe aliased to 'sp' ...
	sp "github.com/scipipe/scipipe"
	// ... and the scipipe component library aliased to 'spc' for brevity.
	spc "github.com/scipipe/scipipe/components"
)

func main() {
	wf := sp.NewWorkflow("my_wf", 4)
	filesInDirectory := spc.NewFileGlobber(wf, "files_in_dir", "mydir/*")

	hReplacer := wf.NewProc("h_replacer", "cat {i:in} > {o:out}")
	hReplacer.In("in").From(filesInDirectory.Out())
	hReplacer.SetOut("out", "{i:in}_file.txt") // <-- See this line, for how to re-use a previous file path

	wf.Run()
}
```

(Note that output files created this way will end up in the same input directory "mydir", because their outputs are based on the full path of the input files).

**Comment by PaschalisAthan** [comment]
That worked like a charm!
Thank you very much for your quick answer Samuel. I was completely unaware of the Scipipe Components.
Also, thanks for letting me know about scipipe gitter chat. I joined the chat in case I need some help in the future!

**Comment by samuell** [comment]
@PaschalisAthan 
> That worked like a charm!
Cool

> I joined the chat in case I need some help in the future!
Great :)

Btw, one caveat which is good to notice unless you did already: One problem with static paths is that execution of SciPipe tasks happen inside a temporary directory, under the script's directory. This is why sometimes you see in the logs that SciPipe adds `../` before the paths of input filenames, to get out of that temp directory before going into the correct dirs. When using the place holder patterns (`{i:in}` and the like), this is done automatically, but if you start using absolute static paths, you need to keep this in mind yourself, which can quite quickly bite you (I tell this from experience :D).
